- whole/src/main/java/model/dao/MarketDAO.java
- whole/src/main/webapp/WEB-INF/itemDetail.jsp
itemDetail.jsp에 날짜 출력 안되던 오류 수정
이 작업은 뭐에 대한거고 어쩌구저쩌구
> [fix/#2]날짜 출력 오류 고치기

- whole/src/main/webapp/WEB-INF/market/market_view_postlist.jsp
- whole/src/main/webapp/WEB-INF/user/loginForm.jsp
- whole/src/main/webapp/css/header.css
- whole/src/main/webapp/css/login.css
> [add/#11] 헤더붙임

- whole/src/main/webapp/WEB-INF/itemDetail.jsp
- whole/src/main/webapp/WEB-INF/market/market_view_postlist.jsp
> [fix#15]img 경로 수정 

- whole/src/main/java/controller/food/FoodUpdateController.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/webapp/WEB-INF/user/sign_up_2.jsp
> [add/#23] FoodManager 추가

- whole/src/main/java/model/dao/FoodDAO.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/java/model/service/MarketManager.java
- whole/src/main/java/test/FoodTest.java
- whole/src/main/resources/mybatis-config.xml
mybatis-config.xml파일 추가 및 FoodEntity에 FoodDto로 변경
> [add/ #25] mybatis-config.xml파일 추가 및 FoodEntity에 FoodDto로 변경

- whole/src/main/java/model/dao/mybatis/mapper/StatisticsMapper.java
- whole/src/main/resources/log4j.properties
- whole/src/main/resources/mybatis-config.xml
log4j.properties 생성
StatisticsMapper interface 추가
> [add/#25]  log4j.properties 생성 및 StatisticsMapper interface 추가

- whole/src/main/java/controller/food/FoodCreateController.java
- whole/src/main/java/controller/food/FoodUpdateController.java
- whole/src/main/java/model/dto/FoodDTO.java
FoodCreateController 완 
아직 jsp 파일 없어서 테스트 x
대략적인 로직 완성
> [feat/#23] FoodCreateController 완

- whole/src/main/java/controller/food/FoodDeleteController.java
- whole/src/main/java/controller/user/LoginController.java
- whole/src/main/java/controller/user/LogoutController.java
- whole/src/main/java/controller/user/UserSessionUtils.java
- whole/src/main/java/model/dao/FoodDAO.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
FoodDeleteController추가
myRefg jsp 파일 추가
이 작업은 뭐에 대한거고 어쩌구저쩌구
> [add/#29] 냉장고 jsp, controller 추가

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/webapp/WEB-INF/fragments/footer.jsp
- whole/src/main/webapp/WEB-INF/fragments/header.jsp
- whole/src/main/webapp/WEB-INF/market/market_view_postlist.jsp
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
- whole/src/main/webapp/loginTest.jsp
이런 걸 했답니다
<%@ include file="../fragments/header.jsp"%>
로 헤더 추가해주믄 됩니다~
클릭 안되면 
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
맨 위에 꼭 추가해주기
> [refactor/#31] header footer 파일 별도로 추가 

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/FoodDeleteController.java
- whole/src/main/java/controller/food/ListFoodController.java
- whole/src/main/java/controller/food/SearchFoodTitleController.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
ListFoodController 나만의 냉장고 화면에 구현
mapping에 화면 연결
> [add/#29] ListFoodController구현

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/ViewFoodController.java
- whole/src/main/java/model/dao/FoodDAO.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/webapp/WEB-INF/myRefg/foodDetail.jsp
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
나만의 냉장고 상세보기
foodDetail.jsp 추가
> [add/#29]foodDetail.jsp 추가

- whole/src/main/java/model/dao/FoodDAO.java
- whole/src/main/webapp/WEB-INF/myRefg/foodDetail.jsp
type 화면 출력할 수 있게..
foodDao select문 foodType추가
> [fix/#29]foodDao select문 foodType추가

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/FoodCreateController.java
- whole/src/main/java/controller/user/LoginController.java
- whole/src/main/java/controller/user/UserSessionUtils.java
- whole/src/main/java/model/dao/UserDAO.java
- whole/src/main/java/util/FoodTypeUtil.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
- whole/src/main/webapp/WEB-INF/myRefg/postForm.jsp
- whole/src/main/webapp/css/myRefg/postForm.css
> [feat/#29] 글작성 중간과정

- whole/src/main/java/controller/user/LoginController.java
- whole/src/main/java/model/dao/UserDAO.java
- whole/src/main/java/model/service/UserManager.java
session에 userId 저장 
session에 userId 저장 
내 id에 해당하는 글만 출력하기 위함
LoginController에서 session.setAttribute(UserSessionUtils.USER_SESSION_KEY_ID, userId.toString()); 로 저장
> [feat/#37] session에 userId 저장 

- whole/src/main/webapp/WEB-INF/myRefg/foodDetail.jsp
- whole/src/main/webapp/css/item_detail.css
foodDetial 수정,삭제,장터이동 버튼 추가
css반영 안돼서 못 했어요..
> [feat/#29] foodDetial 수정,삭제,장터이동 버튼 추가

- whole/pom.xml
- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/ListFoodController.java
- whole/src/main/java/model/dao/FoodDAO.java
- whole/src/main/java/model/dao/UserDAO.java
- whole/src/main/java/model/dao/mybatis/StatisMapperRepository.java
- whole/src/main/java/model/dao/mybatis/mapper/StatisticsMapper.java
- whole/src/main/java/model/service/FoodManager.java
- whole/src/main/java/model/service/UserManager.java
- whole/src/main/java/test/FoodTest.java
- whole/src/main/resources/mybatis-config.xml
- whole/src/main/webapp/WEB-INF/user/loginForm.jsp
**pr전에 오류가 없는지 다시 한 번 확인합시다~!
1. pr 제목 형식 :  [type/#n]작업 내용 (n은 해당 작업 이슈번호)
예시 : [fix/#6]로그인 에러 고치기
2. 작업한 내용 간단하게 해주고 상세한 설명, 캡쳐본 올려주면 됩니다.
3. 왼쪽에 태그 선택해주기(pr 대상, 작업 유형, 작업자)
4. 이 내용 지우고 ------------------ 아래 내용만 업로드해주면 됨
--------------------
1. 로그인 한 사용자의 냉장고 음식만 출력
2. myBatis로 통계 dao 작성 -> 아직은 자바 파일로만 테스트 가능 
작업 내용을 참고하십쇼
> [add/#25]냉장고 기능 구현

- whole/src/main/java/controller/food/FoodCreateController.java
- whole/src/main/java/model/dto/FoodDTO.java
- whole/src/main/java/util/FoodTypeUtil.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
- whole/src/main/webapp/WEB-INF/myRefg/postForm.jsp
- whole/src/main/webapp/css/myRefg/postForm.css
나만의 냉장고 글쓰기 기능 추가
나만의 냉장고 전체화면에서 글쓰기 버튼 추가
나만의 냉장고 글쓰기 기능 추가
Utils 파일에 red, blue 판별하는 함수 추가(FoodDAO에 있는거 복붙)
> [feat/#37] 나만의 냉장고 글쓰기 기능 추가

- whole/src/main/java/controller/food/ListFoodController.java
- whole/src/main/java/model/dao/mybatis/mapper/StatisticsMapper.java
- whole/src/main/java/model/service/StatisticsManager.java
- whole/src/main/java/model/service/UserManager.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
StatisticsManager 클래스 추가
ListFoodController에 신호등 구현 추가
냉장고 헤더에 신호등 구현
이하..동문
> [add/#25]신호등 구현

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/FoodDeleteController.java
- whole/src/main/java/controller/food/ViewFoodController.java
- whole/src/main/webapp/WEB-INF/myRefg/foodDetail.jsp
deleteFoodDetail 수정 완
파라미터 안넘어가서.. 고생 오지게 하무ㅜㅜㅜㅜㅜㅜ
<c:param name='myPostId' value='${param.postId}'/>로 파라미터 넘겼습니다
> [feat/#29] deleteFoodDetail 수정 완

- whole/src/main/java/controller/ViewPostController.java
- whole/src/main/java/controller/food/ListFoodController.java
- whole/src/main/java/model/dao/mybatis/StatisMapperRepository.java
- whole/src/main/java/model/dao/mybatis/mapper/StatisticsMapper.java
- whole/src/main/java/model/service/FoodstaticsManager.java
- whole/src/main/java/util/FoodTypeUtil.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
if(빨간불이면)
print(”대신 이런 음식은 어때요ㅐ? 하고 초록 음식 5개 랜덤으로 주르륵 보여주기)
else if(초록불이면)
print(”아주 좋아요! 이런 음식도 있어요 하고 초록 음식 5개 랜덤으로 주르륵 보여주기)
else(노란불이면)
print(”이런 음식은 피하세요 (빨간 음식 5개 랜덤 출력) 초록 음식 5개 랜덤으로 주르륵 보여주기”)
> [fix/ #25] 통계 화면 조건 추가 및 기능 구현 완료

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/FoodUpdateController.java
- whole/src/main/webapp/WEB-INF/myRefg/foodDetail.jsp
- whole/src/main/webapp/WEB-INF/myRefg/updateForm.jsp
나만의 냉장고 글 수정 완
나만의 냉장고 글 수정 완
detail 에서 요청 추가 
requestMapping 추가 
updateController 추가
> [feat/#45] 나만의 냉장고 글 수정 완

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/food/ViewFoodController.java
- whole/src/main/java/controller/user/LogoutController.java
- whole/src/main/webapp/WEB-INF/myRefg/myRefgList.jsp
- whole/src/main/webapp/WEB-INF/user/mypage.jsp
> [add/#66]로그아웃 기능 구현

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/user/UserMarketController.java
- whole/src/main/java/model/dao/MarketDAO.java
- whole/src/main/java/model/service/MarketManager.java
- whole/src/main/webapp/WEB-INF/user/my_market.jsp
- whole/src/main/webapp/WEB-INF/user/mypage.jsp
마이페이지 내가 쓴 글 출력
이 작업은 뭐에 대한거고 어쩌구저쩌구
> [add/#68]마이페이지 내가 쓴 글 출력

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/market/UpdateMarketController.java
- whole/src/main/java/model/dao/MarketDAO.java
- whole/src/main/java/model/dto/MarketDTO.java
- whole/src/main/java/model/service/MarketManager.java
- whole/src/main/webapp/WEB-INF/itemDetail.jsp
- whole/src/main/webapp/WEB-INF/market/market_post_update.jsp
> [feat/#64] 마켓업데이트

- whole/src/main/java/controller/RequestMapping.java
- whole/src/main/java/controller/user/UpdateUserController.java
- whole/src/main/java/model/dao/mybatis/UpdatePwRepository.java
- whole/src/main/java/model/dao/mybatis/mapper/UpdatePwMapper.java
- whole/src/main/java/model/service/UpdateUserManager.java
- whole/src/main/resources/mybatis-config.xml
- whole/src/main/webapp/WEB-INF/user/updatepw.jsp
비밀번호 변경 구현 완료
기존 비밀번호가 minyoung이었는데 minmin으로 바꿈
db적용 됩니다
>  [add /#58] 비밀번호 변경 구현 완료
